// <auto-generated />
using GlassSearch.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlassSearch.Core.Migrations
{
    [DbContext(typeof(GlassDbContext))]
    [Migration("20230309155539_DocumentSeedData")]
    partial class DocumentSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GlassSearch.Core.Data.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Aut neque architecto nam. Cum et rerum et molestiae dolorum ut dolor. Velit eligendi dolores quam voluptatem. Rerum quam mollitia consequuntur commodi ex. Voluptas nam sunt quasi vel est enim soluta autem. Et est ut asperiores rem quam quis consequatur distinctio.",
                            Title = "autem dolorem corporis"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Commodi dolor reprehenderit sit quam consequatur corporis qui assumenda facilis. Consequuntur est aut vero praesentium doloremque autem et fugit sunt. Assumenda facilis adipisci laboriosam necessitatibus non neque rerum voluptatem culpa.",
                            Title = "ut quos quia"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Recusandae possimus est sapiente et quas vitae. Officia sed qui aut in minima rerum similique. Est nisi quas distinctio ut ipsam ipsa saepe sequi quia. Porro fugiat reiciendis sequi officiis. Explicabo quod id doloribus iure. Rerum omnis eligendi nulla impedit mollitia sit in laboriosam placeat.",
                            Title = "similique rem inventore"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Dolorem tempora accusantium commodi nisi dicta et omnis aliquid est. Rerum sint quam et. Quidem qui earum.",
                            Title = "quidem qui culpa"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Dolores unde dolores voluptatem voluptate. Odio et nihil hic. Omnis quam consequatur deleniti eos et omnis et id. Accusantium adipisci doloribus deserunt non molestiae. Qui qui aut cumque eum. Laboriosam doloribus rerum ab id veniam harum possimus aut omnis.",
                            Title = "at et doloremque"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Quis ut consequatur nostrum in maiores perferendis excepturi dolores. Quo totam delectus ad itaque consequuntur. Quasi sint autem delectus amet commodi.",
                            Title = "vel enim dolores"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Dolores molestiae quibusdam omnis dolor temporibus sequi id ut est. Eum aut nemo deserunt. Repellat qui non quia et id. Dolores aut et praesentium qui facere eius dignissimos quis.",
                            Title = "laboriosam ut voluptatem"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Consequatur perspiciatis atque amet occaecati dolores dolor ut. Sapiente doloribus voluptatem error et ut quidem quo voluptas. Ratione ab quibusdam voluptatem est. Praesentium minima iure laboriosam debitis eum. Atque quod et quod neque.",
                            Title = "voluptas odit dolorem"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Ex dolorem et dolores non enim sunt est cupiditate. Nisi consequatur aut. Similique occaecati perspiciatis. In omnis voluptas. Quis cum distinctio vel repellat quibusdam.",
                            Title = "asperiores quia voluptatem"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Nesciunt consectetur distinctio possimus totam et voluptates eos fuga. Voluptas cumque maxime aut cupiditate cumque. Et distinctio repellendus.",
                            Title = "et ut asperiores"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
